language: ruby
rvm:
- 2.6.3

branches:
  only:
  - travis
  - travis-universal
  except:
  - master

script:
  - bundle exec rspec
  - |
    platform=linux
    wget -cq https://github.com/coverallsapp/coverage-reporter/releases/download/v0.1.9/coveralls-$platform.tar.gz -O - | tar -xz
    if [[ $(curl -H "Accept: application/vnd.github.3.raw" https://api.github.com/repos/coverallsapp/coverage-reporter/contents/checksums/$platform?ref=v0.1.9) == `openssl sha256 coveralls` ]];
    then ./coveralls; else echo 'CHECKSUM ERROR'; exit 1; fi

notifications:
  email: false
