name: Test Coverage-Reporter

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_and_test:
    name: Test on Ubuntu 22.04
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        arch: [x86_64, aarch64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.7
          bundler-cache: true

      # For pre-release testing only
      - name: Install unzip
        run: sudo apt-get install unzip -y

      - name: Run Tests
        run: bundle exec rspec

      # For pre-release testing only
      - name: Download, unzip and run x86_64 binary
        run: |
          curl -sL https://github.com/coverallsapp/coverage-reporter/actions/runs/10950279748/artifacts/1955825113 -o coveralls-linux-x86_64.zip
          unzip coveralls-linux-x86_64.zip
          ./coveralls-linux-x86_64
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

      # For pre-release testing only
      - name: Download, unzip and run aarch64 binary
        run: |
          curl -sL https://github.com/coverallsapp/coverage-reporter/actions/runs/10950279748/artifacts/1955825110 -o coveralls-linux-aarch64.zip
          unzip coveralls-linux-aarch64.zip
          ./coveralls-linux-aarch64
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
