name: Test Coverage-Reporter

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_and_test:
    name: Test on Ubuntu 22.04
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        arch: [x86_64, aarch64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.7
          bundler-cache: true

      - name: Install Ruby dependencies
        run: bundle install

      - name: Run Tests
        run: bundle exec rspec

      # For pre-release testing only
      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      # For pre-release testing only
      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      # For pre-release testing only
      - name: Authenticate GitHub CLI
        run: gh auth login --with-token
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # For pre-release testing only
      - name: Download x86_64 artifact
        run: |
          gh run download 10950279748 --name coveralls-linux-x86_64 --dir ./

      # For pre-release testing only
      - name: Unzip and run x86_64 binary
        run: |
          unzip coveralls-linux-x86_64.zip
          ./coveralls-linux-x86_64
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

      # For pre-release testing only
      - name: Download aarch64 artifact
        run: |
          gh run download 10950279748 --name coveralls-linux-aarch64 --dir ./

      # For pre-release testing only
      - name: Unzip and run aarch64 binary
        run: |
          unzip coveralls-linux-aarch64.zip
          ./coveralls-linux-aarch64
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}